### PR TITLE
Luyu Jin (lj1035) Assignment4

### PR DESCRIPTION
**Pull request by lj1035**

### CODE REVIEW

**Comment by ds-ga-1007** [comment]
Hi there, there is something wrong with your submission, which has conflicts must be solved.
Please double check and resubmit.
Conflicting files: .DS_store.

**Comment by lj1035** [comment]
Should I still fork the assignment4 repository from the ds-ga-1007 user? The repository now contains all students' submissions which include the .DS_store file. This file is not the same as my local file so I cannot merge.

**Comment by ds-ga-1007** [comment]
Have you modified the calendar.usholiday at the top level? If so, then you need to revert any changes to that file before sending a pull request.

**Comment by lj1035** [comment]
I've already uploaded the revised assignment. Thanks!

**Pull request closed without merging**
